"""Pre-built glossary of common Japanese terms for RPG/adult game translation.

Users can load these from the Settings > Glossary tab. Each category can be
loaded independently. Entries never overwrite user-defined glossary terms.
"""

# ── Body / anatomy ──────────────────────────────────────────────
BODY = {
    "おまんこ": "pussy",
    "マンコ": "pussy",
    "まんこ": "pussy",
    "おちんちん": "cock",
    "ちんちん": "cock",
    "チンポ": "cock",
    "ちんぽ": "cock",
    "チンコ": "cock",
    "ペニス": "penis",
    "おっぱい": "breasts",
    "オッパイ": "breasts",
    "おしり": "butt",
    "お尻": "butt",
    "クリトリス": "clit",
    "アナル": "anal",
    "子宮": "womb",
    "膣": "vagina",
    "乳首": "nipples",
    "乳房": "breasts",
    "陰茎": "penis",
    "睾丸": "testicles",
    "金玉": "balls",
    "太もも": "thighs",
    "恥丘": "pubic mound",
}

# ── Sexual acts / states ────────────────────────────────────────
ACTS = {
    "セックス": "sex",
    "フェラ": "blowjob",
    "フェラチオ": "fellatio",
    "パイズリ": "titjob",
    "手コキ": "handjob",
    "クンニ": "cunnilingus",
    "中出し": "creampie",
    "顔射": "facial",
    "射精": "ejaculation",
    "絶頂": "climax",
    "オーガズム": "orgasm",
    "イク": "cumming",
    "いく": "cumming",
    "レイプ": "rape",
    "輪姦": "gang rape",
    "和姦": "consensual sex",
    "処女": "virgin",
    "童貞": "virgin",
    "妊娠": "pregnancy",
    "種付け": "impregnation",
    "搾乳": "milking",
    "潮吹き": "squirting",
    "媚薬": "aphrodisiac",
    "催眠": "hypnosis",
    "触手": "tentacle",
    "孕ませ": "impregnation",
    "寝取り": "cuckolding",
    "寝取られ": "netorare",
    "痴漢": "groping",
    "露出": "exhibitionism",
    "調教": "training",
    "奴隷": "slave",
    "淫乱": "lewd",
    "変態": "pervert",
    "エッチ": "lewd",
    "おかず": "fap material",
}

# ── RPG / game terms ────────────────────────────────────────────
RPG = {
    "勇者": "Hero",
    "魔王": "Demon Lord",
    "魔物": "monster",
    "冒険者": "adventurer",
    "ギルド": "guild",
    "ダンジョン": "dungeon",
    "宿屋": "inn",
    "酒場": "tavern",
    "武器屋": "weapon shop",
    "道具屋": "item shop",
    "防具屋": "armor shop",
    "教会": "church",
    "城": "castle",
    "王国": "kingdom",
    "魔法": "magic",
    "スキル": "skill",
    "経験値": "EXP",
    "レベルアップ": "level up",
    "ゴールド": "gold",
    "ポーション": "potion",
    "エリクサー": "elixir",
    "仲間": "companion",
    "装備": "equipment",
}

# ── Eroge status / corruption ──────────────────────────────────
STATUS = {
    "好感度": "affection",
    "淫乱度": "lewdness",
    "堕落": "corruption",
    "純潔": "purity",
    "貞操": "chastity",
    "快楽": "pleasure",
    "感度": "sensitivity",
    "恥辱": "shame",
    "屈辱": "humiliation",
    "服従": "submission",
    "支配": "domination",
    "魅了": "charm",
    "誘惑": "seduction",
    "欲情": "lust",
    "発情": "in heat",
    "興奮": "arousal",
    "売春": "prostitution",
    "娼婦": "prostitute",
    "遊郭": "brothel",
    "ハーレム": "harem",
    "逆ハーレム": "reverse harem",
    "愛人": "lover",
    "恋人": "lover",
    "許嫁": "fiance",
    "婚約者": "fiance",
}

# ── Fantasy races / classes ────────────────────────────────────
RACES = {
    "エルフ": "elf",
    "ダークエルフ": "dark elf",
    "ドワーフ": "dwarf",
    "獣人": "beastkin",
    "竜人": "dragonkin",
    "吸血鬼": "vampire",
    "サキュバス": "succubus",
    "インキュバス": "incubus",
    "ゴブリン": "goblin",
    "オーク": "orc",
    "スライム": "slime",
    "オーガ": "ogre",
    "リッチ": "lich",
    "ゾンビ": "zombie",
    "ケルベロス": "Cerberus",
    "ミノタウロス": "Minotaur",
    "ラミア": "lamia",
    "ハーピー": "harpy",
    "アラクネ": "arachne",
    "ケンタウロス": "centaur",
    "マーメイド": "mermaid",
    "妖精": "fairy",
    "天使": "angel",
    "悪魔": "demon",
    "魔族": "demon race",
    "人間": "human",
    "戦士": "warrior",
    "魔法使い": "mage",
    "僧侶": "priest",
    "盗賊": "thief",
    "騎士": "knight",
    "聖騎士": "paladin",
    "暗黒騎士": "dark knight",
    "忍者": "ninja",
    "侍": "samurai",
    "召喚士": "summoner",
    "錬金術師": "alchemist",
    "踊り子": "dancer",
    "姫騎士": "princess knight",
    "女騎士": "female knight",
    "女戦士": "female warrior",
    "魔女": "witch",
    "巫女": "shrine maiden",
    "シスター": "sister",
    "メイド": "maid",
    "くノ一": "kunoichi",
}

# ── Clothing / attire ──────────────────────────────────────────
CLOTHING = {
    "鎧": "armor",
    "ローブ": "robe",
    "ビキニアーマー": "bikini armor",
    "レオタード": "leotard",
    "制服": "uniform",
    "水着": "swimsuit",
    "下着": "underwear",
    "パンツ": "panties",
    "ブラ": "bra",
    "ストッキング": "stockings",
    "ガーターベルト": "garter belt",
    "ニーソックス": "thigh-highs",
    "チャイナドレス": "cheongsam",
    "バニースーツ": "bunny suit",
    "メイド服": "maid outfit",
    "巫女服": "shrine maiden outfit",
    "拘束具": "restraints",
    "首輪": "collar",
    "手枷": "handcuffs",
    "目隠し": "blindfold",
    "猿轡": "ball gag",
}

# ── Gambling / poker ─────────────────────────────────────────────
GAMBLING = {
    # Card games
    "ポーカー": "poker",
    "ブラックジャック": "blackjack",
    "バカラ": "baccarat",
    "トランプ": "playing cards",
    "カード": "card",
    "手札": "hand",
    "山札": "deck",
    "切り札": "trump card",
    "ジョーカー": "joker",
    "ババ抜き": "Old Maid",
    "神経衰弱": "Concentration",
    "大富豪": "President",
    "七並べ": "Sevens",
    # Poker hands
    "ロイヤルストレートフラッシュ": "royal flush",
    "ストレートフラッシュ": "straight flush",
    "フォーカード": "four of a kind",
    "フルハウス": "full house",
    "フラッシュ": "flush",
    "ストレート": "straight",
    "スリーカード": "three of a kind",
    "ツーペア": "two pair",
    "ワンペア": "one pair",
    "ブタ": "high card",
    "役": "hand",
    # Poker actions
    "レイズ": "raise",
    "コール": "call",
    "フォールド": "fold",
    "チェック": "check",
    "ベット": "bet",
    "オールイン": "all-in",
    "ブラフ": "bluff",
    "ディーラー": "dealer",
    # Gambling general
    "ギャンブル": "gambling",
    "賭け": "bet",
    "賭ける": "to bet",
    "カジノ": "casino",
    "スロット": "slot machine",
    "ルーレット": "roulette",
    "サイコロ": "dice",
    "チップ": "chips",
    "配当": "payout",
    "倍率": "odds",
    "大当たり": "jackpot",
    "ジャックポット": "jackpot",
    "一攫千金": "hitting the jackpot",
    "勝負": "match",
    "勝ち": "win",
    "負け": "loss",
    "引き分け": "draw",
    "イカサマ": "cheating",
    "いかさま": "cheating",
    # Strip poker / penalty games
    "脱衣ポーカー": "strip poker",
    "脱衣麻雀": "strip mahjong",
    "脱衣": "stripping",
    "脱ぐ": "undress",
    "脱がす": "strip someone",
    "脱がされる": "get stripped",
    "罰ゲーム": "penalty game",
    "罰": "penalty",
    "一枚脱ぐ": "take off one piece",
    "全裸": "fully nude",
    "半裸": "half-naked",
    "裸": "naked",
    "恥ずかしい": "embarrassing",
    "丸見え": "fully exposed",
    "見せる": "show",
    "晒す": "expose",
    "賭け事": "gambling",
    "負けたら脱ぐ": "strip if you lose",
}

# ── Common expressions ──────────────────────────────────────────
EXPRESSIONS = {
    "くっ": "Kuh...",
    "ふふ": "Fufu",
    "うふふ": "Ufufu",
    "あはは": "Ahaha",
    "えへへ": "Ehehe",
    "くすくす": "Hehe",
    "ぐぬぬ": "Grr...",
    "きゃー": "Kyaa!",
    "やだ": "No way",
    "ちょっと": "Hey",
    "すごい": "Amazing",
    "やめて": "Stop it",
    "ダメ": "No",
    "だめ": "No",
    "お願い": "Please",
    "ありがとう": "Thank you",
    "ごめんなさい": "I'm sorry",
    "ごめんね": "Sorry",
    "バカ": "Idiot",
    "馬鹿": "Idiot",
    "うるさい": "Shut up",
    "助けて": "Help me",
    "気持ちいい": "It feels good",
    "いやらしい": "Naughty",
}

# ── All categories with labels ──────────────────────────────────
CATEGORIES = {
    "Body / Anatomy": BODY,
    "Sexual Acts": ACTS,
    "Status / Corruption": STATUS,
    "Fantasy Races / Classes": RACES,
    "Clothing / Attire": CLOTHING,
    "Gambling / Poker": GAMBLING,
    "RPG Terms": RPG,
    "Common Expressions": EXPRESSIONS,
}


def get_all_defaults() -> dict:
    """Return all default glossary entries merged into one dict."""
    merged = {}
    for cat_entries in CATEGORIES.values():
        merged.update(cat_entries)
    return merged
