"""Pre-built glossary of common Japanese terms for RPG/adult game translation.

Users can load these from the Settings > Glossary tab. Each category can be
loaded independently. Entries never overwrite user-defined glossary terms.
"""

# ── Body / anatomy ──────────────────────────────────────────────
BODY = {
    "おまんこ": "pussy",
    "マンコ": "pussy",
    "まんこ": "pussy",
    "おちんちん": "cock",
    "ちんちん": "cock",
    "チンポ": "cock",
    "ちんぽ": "cock",
    "チンコ": "cock",
    "ペニス": "penis",
    "おっぱい": "breasts",
    "オッパイ": "breasts",
    "おしり": "butt",
    "お尻": "butt",
    "クリトリス": "clit",
    "アナル": "anal",
    "子宮": "womb",
    "膣": "vagina",
    "乳首": "nipples",
    "乳房": "breasts",
    "陰茎": "penis",
    "睾丸": "testicles",
    "金玉": "balls",
    "太もも": "thighs",
    "恥丘": "pubic mound",
    "お股": "crotch",
    "秘部": "genitals",
    "尻": "ass",
    "胸": "breasts",
    "腰": "waist",
    "股間": "crotch",
    "肛門": "anus",
    "亀頭": "glans",
    "乳輪": "areola",
    "肉棒": "cock",
}

# ── Sexual acts / states ────────────────────────────────────────
ACTS = {
    "セックス": "sex",
    "フェラ": "blowjob",
    "フェラチオ": "fellatio",
    "パイズリ": "titjob",
    "手コキ": "handjob",
    "クンニ": "cunnilingus",
    "中出し": "creampie",
    "顔射": "facial",
    "射精": "ejaculation",
    "絶頂": "climax",
    "オーガズム": "orgasm",
    "イク": "cumming",
    "いく": "cumming",
    "レイプ": "rape",
    "輪姦": "gang rape",
    "和姦": "consensual sex",
    "処女": "virgin",
    "童貞": "virgin",
    "妊娠": "pregnancy",
    "種付け": "impregnation",
    "搾乳": "milking",
    "潮吹き": "squirting",
    "媚薬": "aphrodisiac",
    "催眠": "hypnosis",
    "触手": "tentacle",
    "孕ませ": "impregnation",
    "寝取り": "cuckolding",
    "寝取られ": "netorare",
    "痴漢": "groping",
    "露出": "exhibitionism",
    "調教": "training",
    "奴隷": "slave",
    "淫乱": "lewd",
    "変態": "pervert",
    "エッチ": "lewd",
    "おかず": "fap material",
    "オナニー": "masturbation",
    "ザーメン": "cum",
    "勃起": "erection",
    "膣内": "vaginal",
    "挿入": "penetration",
    "精液": "semen",
    "性感帯": "erogenous zone",
    "我慢汁": "precum",
    "口内射精": "oral creampie",
    "手マン": "fingering",
    "前戯": "foreplay",
    "ロリコン": "lolicon",
    "イラマチオ": "irrumatio",
    "素股": "thighjob",
    "尻コキ": "assjob",
    "ぶっかけ": "cumshot",
    "受精": "fertilized",
    "出産": "childbirth",
    "キス": "kiss",
    "膣内射精": "creampie",
    "膣外射精": "non-creampie",
    "乳揉まれ": "fondled",
    "尻揉まれ": "ass groped",
    "愛撫": "caress",
    "陵辱": "violation",
    "乱交": "orgy",
    "逆レイプ": "reverse rape",
    "夜這い": "night crawling",
    "淫語": "dirty talk",
    "喘ぎ声": "moaning",
    "母乳": "breast milk",
    "異種姦": "interspecies sex",
    "近親相姦": "incest",
    "二穴": "double penetration",
    "愛液": "love juice",
    "淫紋": "lewd crest",
    "強姦": "rape",
    "精飲": "cum drinking",
}

# ── RPG / game terms ────────────────────────────────────────────
RPG = {
    # Roles & archetypes
    "勇者": "Hero",
    "魔王": "Demon Lord",
    "魔物": "monster",
    "冒険者": "adventurer",
    "村人": "villager",
    "町人": "townsperson",
    "商人": "merchant",
    "王": "king",
    "王女": "princess",
    "王子": "prince",
    "女王": "queen",
    "領主": "lord",
    "長老": "elder",
    "村長": "village chief",
    # Locations
    "ギルド": "guild",
    "ダンジョン": "dungeon",
    "宿屋": "inn",
    "酒場": "tavern",
    "武器屋": "weapon shop",
    "道具屋": "item shop",
    "防具屋": "armor shop",
    "教会": "church",
    "城": "castle",
    "王国": "kingdom",
    "帝国": "empire",
    "村": "village",
    "町": "town",
    "迷宮": "labyrinth",
    "塔": "tower",
    "洞窟": "cave",
    "森": "forest",
    "砂漠": "desert",
    "火山": "volcano",
    "遺跡": "ruins",
    "神殿": "temple",
    "墓地": "graveyard",
    "闘技場": "arena",
    # Core systems
    "魔法": "magic",
    "スキル": "skill",
    "経験値": "EXP",
    "レベルアップ": "level up",
    "ゴールド": "gold",
    "ポーション": "potion",
    "エリクサー": "elixir",
    "仲間": "companion",
    "装備": "equipment",
    "クエスト": "quest",
    "依頼": "request",
    "報酬": "reward",
    "宝箱": "treasure chest",
    "セーブ": "save",
    "ロード": "load",
    "ゲームオーバー": "Game Over",
    "全滅": "annihilation",
    # Menu / UI
    "並び替え": "Sort",
    "最強装備": "Optimal Equipment",
    "大事なもの": "Key Items",
    "ゲーム終了": "Quit Game",
    "コンティニュー": "Continue",
    "ニューゲーム": "New Game",
    "購入する": "Buy",
    "売却する": "Sell",
    "全て外す": "Unequip All",
    "キャンセル": "Cancel",
    "オプション": "Options",
    "タイトルへ": "To Title",
    "ステータス": "Status",
    "やっぱりやめる": "Never mind",
    "初めから": "Start",
    "回想する": "Recollection",
    "討伐": "Extermination",
    "邪気": "Miasma",
    "所持金": "Money",
    "持ち物": "Inventory",
    "道具": "Items",
    "使う": "Use",
    "捨てる": "Discard",
    "確認": "Confirm",
    "戻る": "Back",
    "決定": "OK",
    "次へ": "Next",
    "閉じる": "Close",
    # Locations
    "避暑地": "summer resort",
    "別荘": "villa",
    "雑木林": "thicket",
    "川辺": "riverbank",
}

# ── Combat / battle ──────────────────────────────────────────────
COMBAT = {
    # Targeting
    "敵単体": "Single Enemy",
    "敵全体": "All Enemies",
    "敵１体": "One Enemy",
    "敵２体": "Two Enemies",
    "味方単体": "Single Ally",
    "味方全体": "All Allies",
    "味方一人": "One Ally",
    "使用者": "User",
    "自分": "Self",
    "ランダム": "Random",
    # Actions
    "攻撃": "Attack",
    "防御": "Defend",
    "逃げる": "Escape",
    "逃走": "Escape",
    "戦う": "Fight",
    "アイテム": "Item",
    "必殺技": "Special Move",
    "奥義": "Secret Art",
    "詠唱": "Chanting",
    "召喚": "Summon",
    "回復": "Recovery",
    "治療": "Heal",
    "蘇生": "Revive",
    "復活": "Revival",
    "反撃": "Counter",
    "連続攻撃": "Combo Attack",
    "全体攻撃": "Area Attack",
    "先制攻撃": "Preemptive Strike",
    "不意打ち": "Ambush",
    "会心の一撃": "Critical Hit",
    "会心": "Critical",
    "命中": "Hit",
    "回避": "Evasion",
    "ミス": "Miss",
    # Status effects
    "毒": "Poison",
    "麻痺": "Paralysis",
    "睡眠": "Sleep",
    "暗闇": "Blindness",
    "沈黙": "Silence",
    "混乱": "Confusion",
    "石化": "Petrification",
    "即死": "Instant Death",
    "戦闘不能": "Knocked Out",
    "気絶": "Stunned",
    "出血": "Bleeding",
    "呪い": "Curse",
    "狂戦士": "Berserk",
    "魔法反射": "Magic Reflection",
    "無敵": "Invincible",
    "透明": "Invisible",
    "再生": "Regeneration",
    "弱点": "Weakness",
    "耐性": "Resistance",
    "吸収": "Absorb",
    "バフ": "Buff",
    "デバフ": "Debuff",
    # Elements
    "火": "Fire",
    "氷": "Ice",
    "雷": "Thunder",
    "水": "Water",
    "風": "Wind",
    "土": "Earth",
    "光": "Light",
    "闇": "Darkness",
    "聖": "Holy",
    "無": "None",
    "物理": "Physical",
    "神聖": "Holy",
    "暗黒": "Dark",
    "木": "Wood",
    "地": "Earth",
    "凍結": "Frozen",
    "炎": "Flame",
    "大地": "Earth",
    "ダメージ": "Damage",
    "黒魔法": "Black Magic",
    "白魔法": "White Magic",
    "全体": "All",
    "敵": "Enemy",
    "味方": "Ally",
    "属性": "Attribute",
    # Additional
    "状態異常": "Status Ailment",
    "ターン終了": "End Turn",
    "不死身": "Immortal",
    "激昂": "Enraged",
}

# ── Stats / parameters ───────────────────────────────────────────
STATS = {
    "最大ＨＰ": "Max HP",
    "最大ＭＰ": "Max MP",
    "ＨＰ": "HP",
    "ＭＰ": "MP",
    "ＴＰ": "TP",
    "攻撃力": "Attack",
    "防御力": "Defense",
    "魔力": "Magic Power",
    "魔法攻撃": "Magic Attack",
    "魔法防御": "Magic Defense",
    "魔防": "Magic Defense",
    "敏捷性": "Agility",
    "敏捷": "Agility",
    "素早さ": "Speed",
    "運": "Luck",
    "命中率": "Hit Rate",
    "回避率": "Evasion Rate",
    "会心率": "Critical Rate",
    "体力": "Stamina",
    "知力": "Intelligence",
    "精神": "Spirit",
    "魅力": "Charisma",
    "力": "Strength",
    "知性": "Intelligence",
    "器用": "Dexterity",
    "職業": "Job",
    "特技": "Special Skill",
    "技": "Technique",
}

# ── Equipment / items ────────────────────────────────────────────
EQUIPMENT = {
    # Slots
    "武器": "Weapon",
    "盾": "Shield",
    "頭防具": "Headgear",
    "身体防具": "Body Armor",
    "腕防具": "Arm Guard",
    "装飾品": "Accessory",
    # Weapon types
    "剣": "Sword",
    "大剣": "Greatsword",
    "短剣": "Dagger",
    "槍": "Spear",
    "斧": "Axe",
    "弓": "Bow",
    "杖": "Staff",
    "本": "Book",
    "鞭": "Whip",
    "爪": "Claws",
    "拳": "Fist",
    "銃": "Gun",
    "刀": "Katana",
    # Items
    "薬草": "Herb",
    "毒消し": "Antidote",
    "万能薬": "Panacea",
    "魔法の鍵": "Magic Key",
    "テント": "Tent",
    "聖水": "Holy Water",
    "煙玉": "Smoke Bomb",
    "鉱石": "Ore",
    "素材": "Material",
    "レシピ": "Recipe",
    "防具": "Armor",
    "帽子": "Hat",
    "服": "Clothes",
    "指輪": "Ring",
}

# ── Eroge status / corruption ──────────────────────────────────
STATUS = {
    "好感度": "affection",
    "淫乱度": "lewdness",
    "堕落": "corruption",
    "純潔": "purity",
    "貞操": "chastity",
    "快楽": "pleasure",
    "感度": "sensitivity",
    "恥辱": "shame",
    "屈辱": "humiliation",
    "服従": "submission",
    "支配": "domination",
    "魅了": "charm",
    "誘惑": "seduction",
    "欲情": "lust",
    "発情": "in heat",
    "興奮": "arousal",
    "売春": "prostitution",
    "娼婦": "prostitute",
    "遊郭": "brothel",
    "ハーレム": "harem",
    "逆ハーレム": "reverse harem",
    "愛人": "lover",
    "恋人": "lover",
    "許嫁": "fiance",
    "婚約者": "fiance",
    "理性": "sanity",
    "性欲": "libido",
    "絶頂回数": "orgasms",
    "経験人数": "partners",
    "射精量": "cum amount",
    "恐怖": "fear",
    "洗脳": "brainwashing",
    "信頼度": "trust",
    "妊娠回数": "pregnancies",
}

# ── Fantasy races / classes ────────────────────────────────────
RACES = {
    "エルフ": "elf",
    "ダークエルフ": "dark elf",
    "ドワーフ": "dwarf",
    "獣人": "beastkin",
    "竜人": "dragonkin",
    "吸血鬼": "vampire",
    "サキュバス": "succubus",
    "インキュバス": "incubus",
    "ゴブリン": "goblin",
    "オーク": "orc",
    "スライム": "slime",
    "オーガ": "ogre",
    "リッチ": "lich",
    "ゾンビ": "zombie",
    "ケルベロス": "Cerberus",
    "ミノタウロス": "Minotaur",
    "ラミア": "lamia",
    "ハーピー": "harpy",
    "アラクネ": "arachne",
    "ケンタウロス": "centaur",
    "マーメイド": "mermaid",
    "妖精": "fairy",
    "天使": "angel",
    "悪魔": "demon",
    "魔族": "demon race",
    "人間": "human",
    "戦士": "warrior",
    "魔法使い": "mage",
    "僧侶": "priest",
    "盗賊": "thief",
    "騎士": "knight",
    "聖騎士": "paladin",
    "暗黒騎士": "dark knight",
    "忍者": "ninja",
    "侍": "samurai",
    "召喚士": "summoner",
    "錬金術師": "alchemist",
    "踊り子": "dancer",
    "姫騎士": "princess knight",
    "女騎士": "female knight",
    "女戦士": "female warrior",
    "魔女": "witch",
    "巫女": "shrine maiden",
    "シスター": "sister",
    "メイド": "maid",
    "くノ一": "kunoichi",
    "魔術師": "sorcerer",
    "大魔導士": "archmage",
    "忍び": "shinobi",
    # Demons / angels / monsters
    "聖女": "saintess",
    "上級悪魔": "arch demon",
    "魔神": "devil",
    "魔人": "demon",
    "睡魔": "mare",
    "淫魔": "succubus",
    "夢魔": "succubus",
    "大天使": "archangel",
    "権天使": "principality",
    "能天使": "power",
    "力天使": "virtue",
    "主天使": "dominion",
    "智天使": "cherub",
    "飛天魔": "nephilim",
    "堕天使": "fallen angel",
    "鬼": "oni",
    "妖怪": "yokai",
    "式神": "shikigami",
    "幽霊": "ghost",
    "幽鬼": "revenant",
    "デーモン": "daemon",
    "ローパー": "roper",
    "人型": "humanoid",
    "獣型": "beast",
    "触手型": "tentacle type",
    "軟体型": "slime type",
    "虫型": "insect type",
    "竜": "dragon",
    "ドラゴン": "dragon",
    "ワーウルフ": "werewolf",
    "グリフォン": "griffin",
    "ゴーレム": "golem",
    "トロール": "troll",
    "キメラ": "chimera",
    "ワイバーン": "wyvern",
    "フェニックス": "phoenix",
    "狼": "wolf",
    "蜘蛛": "spider",
    "蝙蝠": "bat",
    "蛇": "snake",
}

# ── Clothing / attire ──────────────────────────────────────────
CLOTHING = {
    "鎧": "armor",
    "ローブ": "robe",
    "ビキニアーマー": "bikini armor",
    "レオタード": "leotard",
    "制服": "uniform",
    "水着": "swimsuit",
    "下着": "underwear",
    "パンツ": "panties",
    "ショーツ": "panties",
    "ブラ": "bra",
    "ストッキング": "stockings",
    "ガーターベルト": "garter belt",
    "ニーソックス": "thigh-highs",
    "チャイナドレス": "cheongsam",
    "バニースーツ": "bunny suit",
    "メイド服": "maid outfit",
    "巫女服": "shrine maiden outfit",
    "拘束具": "restraints",
    "首輪": "collar",
    "手枷": "handcuffs",
    "目隠し": "blindfold",
    "猿轡": "ball gag",
    "タイツ": "tights",
    "エプロン": "apron",
    "スカート": "skirt",
    "ドレス": "dress",
    "マント": "cloak",
    "着物": "kimono",
    "浴衣": "yukata",
    "体操服": "gym uniform",
    "ブルマ": "bloomers",
    "スクール水着": "school swimsuit",
}

# ── Gambling / poker ─────────────────────────────────────────────
GAMBLING = {
    # Card games
    "ポーカー": "poker",
    "ブラックジャック": "blackjack",
    "バカラ": "baccarat",
    "トランプ": "playing cards",
    "カード": "card",
    "手札": "hand",
    "山札": "deck",
    "切り札": "trump card",
    "ジョーカー": "joker",
    "ババ抜き": "Old Maid",
    "神経衰弱": "Concentration",
    "大富豪": "President",
    "七並べ": "Sevens",
    # Poker hands
    "ロイヤルストレートフラッシュ": "royal flush",
    "ストレートフラッシュ": "straight flush",
    "フォーカード": "four of a kind",
    "フルハウス": "full house",
    "フラッシュ": "flush",
    "ストレート": "straight",
    "スリーカード": "three of a kind",
    "ツーペア": "two pair",
    "ワンペア": "one pair",
    "ブタ": "high card",
    "役": "hand",
    # Poker actions
    "レイズ": "raise",
    "コール": "call",
    "フォールド": "fold",
    "チェック": "check",
    "ベット": "bet",
    "オールイン": "all-in",
    "ブラフ": "bluff",
    "ディーラー": "dealer",
    # Gambling general
    "ギャンブル": "gambling",
    "賭け": "bet",
    "賭ける": "to bet",
    "カジノ": "casino",
    "スロット": "slot machine",
    "ルーレット": "roulette",
    "サイコロ": "dice",
    "チップ": "chips",
    "配当": "payout",
    "倍率": "odds",
    "大当たり": "jackpot",
    "ジャックポット": "jackpot",
    "一攫千金": "hitting the jackpot",
    "勝負": "match",
    "勝ち": "win",
    "負け": "loss",
    "引き分け": "draw",
    "イカサマ": "cheating",
    "いかさま": "cheating",
    # Strip poker / penalty games
    "脱衣ポーカー": "strip poker",
    "脱衣麻雀": "strip mahjong",
    "脱衣": "stripping",
    "脱ぐ": "undress",
    "脱がす": "strip someone",
    "脱がされる": "get stripped",
    "罰ゲーム": "penalty game",
    "罰": "penalty",
    "一枚脱ぐ": "take off one piece",
    "全裸": "fully nude",
    "半裸": "half-naked",
    "裸": "naked",
    "恥ずかしい": "embarrassing",
    "丸見え": "fully exposed",
    "見せる": "show",
    "晒す": "expose",
    "賭け事": "gambling",
    "負けたら脱ぐ": "strip if you lose",
}

# ── Speaker tags / honorifics ────────────────────────────────────
SPEAKERS = {
    "ご主人様": "Master",
    "マスター": "Master",
    "お嬢様": "Milady",
    "旦那様": "Master",
    "奥様": "Madam",
    "先生": "Teacher",
    "先輩": "Senpai",
    "後輩": "Junior",
    "お兄ちゃん": "Big Brother",
    "お姉ちゃん": "Big Sister",
    "お兄さん": "Mister",
    "お姉さん": "Miss",
    "おじさん": "Old Man",
    "おばさん": "Lady",
    "男": "Man",
    "女": "Woman",
    "少年": "Boy",
    "少女": "Girl",
    "青年": "Young Man",
    "老人": "Old Man",
    "兵士": "Soldier",
    "衛兵": "Guard",
    "店主": "Shopkeeper",
    "受付嬢": "Receptionist",
    "魔法少女": "Magical Girl",
    "ナレーション": "Narration",
    "令嬢": "Young Lady",
    "小悪魔": "Little Devil",
    "付き人": "Attendant",
    "村人たち": "Villagers",
}

# ── Common expressions ──────────────────────────────────────────
EXPRESSIONS = {
    "くっ": "Kuh...",
    "ふふ": "Fufu",
    "うふふ": "Ufufu",
    "あはは": "Ahaha",
    "えへへ": "Ehehe",
    "くすくす": "Hehe",
    "ぐぬぬ": "Grr...",
    "きゃー": "Kyaa!",
    "やだ": "No way",
    "ちょっと": "Hey",
    "すごい": "Amazing",
    "やめて": "Stop it",
    "ダメ": "No",
    "だめ": "No",
    "お願い": "Please",
    "ありがとう": "Thank you",
    "ごめんなさい": "I'm sorry",
    "ごめんね": "Sorry",
    "バカ": "Idiot",
    "馬鹿": "Idiot",
    "うるさい": "Shut up",
    "助けて": "Help me",
    "気持ちいい": "It feels good",
    "いやらしい": "Naughty",
    "メスガキ": "bratty girl",
    "クソガキ": "brat",
    "ガキ": "brat",
    "あん": "Ahn~",
    "んっ": "Mmh",
    "痛い": "It hurts",
    "怖い": "Scary",
    "嬉しい": "Happy",
    "熱い": "Hot",
}

# ── Onomatopoeia / SFX ───────────────────────────────────────────
ONOMATOPOEIA = {
    "ぬるぬる": "slippery",
    "ぷにぷに": "soft and squishy",
    "シコシコ": "stroking",
    "ビンビン": "rock hard",
    "ドピュ": "spurt",
    "ビクビク": "twitching",
    "パンパン": "slapping",
    "ぐちゅぐちゅ": "squelching",
    "ズボズボ": "thrusting",
    "つるつる": "smooth",
    "ドクドク": "throbbing",
    "ヌルヌル": "slippery",
    "ピクピク": "twitching",
    "ズブズブ": "plunging",
    "ジュボジュボ": "slurping",
}

# ── All categories with labels ──────────────────────────────────
CATEGORIES = {
    "Body / Anatomy": BODY,
    "Sexual Acts": ACTS,
    "Status / Corruption": STATUS,
    "Fantasy Races / Classes": RACES,
    "Clothing / Attire": CLOTHING,
    "Gambling / Poker": GAMBLING,
    "RPG Terms": RPG,
    "Combat / Battle": COMBAT,
    "Stats / Parameters": STATS,
    "Equipment / Items": EQUIPMENT,
    "Speaker Tags": SPEAKERS,
    "Common Expressions": EXPRESSIONS,
    "Onomatopoeia / SFX": ONOMATOPOEIA,
}


def get_all_defaults() -> dict:
    """Return all default glossary entries merged into one dict."""
    merged = {}
    for cat_entries in CATEGORIES.values():
        merged.update(cat_entries)
    return merged
