"""Pre-built glossary of common Japanese terms for RPG/adult game translation.

Users can load these from the Settings > Glossary tab. Each category can be
loaded independently. Entries never overwrite user-defined glossary terms.
"""

# ── Body / anatomy ──────────────────────────────────────────────
BODY = {
    "おまんこ": "Pussy",
    "マンコ": "Pussy",
    "まんこ": "Pussy",
    "おちんちん": "Cock",
    "ちんちん": "Cock",
    "チンポ": "Cock",
    "ちんぽ": "Cock",
    "チンコ": "Cock",
    "ペニス": "Penis",
    "おっぱい": "Breasts",
    "オッパイ": "Breasts",
    "おしり": "Butt",
    "お尻": "Butt",
    "クリトリス": "Clit",
    "アナル": "Anal",
    "子宮": "Womb",
    "膣": "Vagina",
    "乳首": "Nipples",
    "乳房": "Breasts",
    "陰茎": "Penis",
    "睾丸": "Testicles",
    "金玉": "Balls",
    "太もも": "Thighs",
    "恥丘": "Pubic Mound",
    "お股": "Crotch",
    "秘部": "Genitals",
    "尻": "Ass",
    "胸": "Breasts",
    "腰": "Waist",
    "股間": "Crotch",
    "肛門": "Anus",
    "亀頭": "Glans",
    "乳輪": "Areola",
    "肉棒": "Cock",
}

# ── Sexual acts / states ────────────────────────────────────────
ACTS = {
    "セックス": "Sex",
    "フェラ": "Blowjob",
    "フェラチオ": "Fellatio",
    "パイズリ": "Titjob",
    "手コキ": "Handjob",
    "クンニ": "Cunnilingus",
    "中出し": "Creampie",
    "顔射": "Facial",
    "射精": "Ejaculation",
    "絶頂": "Climax",
    "オーガズム": "Orgasm",
    "イク": "Cumming",
    "いく": "Cumming",
    "レイプ": "Rape",
    "輪姦": "Gang Rape",
    "和姦": "Consensual Sex",
    "処女": "Virgin",
    "童貞": "Virgin",
    "妊娠": "Pregnancy",
    "種付け": "Impregnation",
    "搾乳": "Milking",
    "潮吹き": "Squirting",
    "媚薬": "Aphrodisiac",
    "催眠": "Hypnosis",
    "触手": "Tentacle",
    "孕ませ": "Impregnation",
    "寝取り": "Cuckolding",
    "寝取られ": "Netorare",
    "痴漢": "Groping",
    "露出": "Exhibitionism",
    "調教": "Training",
    "奴隷": "Slave",
    "淫乱": "Lewd",
    "変態": "Pervert",
    "エッチ": "Lewd",
    "おかず": "Fap Material",
    "オナニー": "Masturbation",
    "ザーメン": "Cum",
    "勃起": "Erection",
    "膣内": "Vaginal",
    "挿入": "Penetration",
    "精液": "Semen",
    "性感帯": "Erogenous Zone",
    "我慢汁": "Precum",
    "口内射精": "Oral Creampie",
    "手マン": "Fingering",
    "前戯": "Foreplay",
    "ロリコン": "Lolicon",
    "イラマチオ": "Irrumatio",
    "素股": "Thighjob",
    "尻コキ": "Assjob",
    "ぶっかけ": "Cumshot",
    "受精": "Fertilized",
    "出産": "Childbirth",
    "キス": "Kiss",
    "膣内射精": "Creampie",
    "膣外射精": "Pullout",
    "乳揉まれ": "Fondled",
    "尻揉まれ": "Ass Groped",
    "愛撫": "Caress",
    "陵辱": "Violation",
    "乱交": "Orgy",
    "逆レイプ": "Reverse Rape",
    "夜這い": "Night Crawling",
    "淫語": "Dirty Talk",
    "喘ぎ声": "Moaning",
    "母乳": "Breast Milk",
    "異種姦": "Interspecies Sex",
    "近親相姦": "Incest",
    "二穴": "Double Penetration",
    "愛液": "Love Juice",
    "淫紋": "Lewd Crest",
    "強姦": "Rape",
    "精飲": "Cum Drinking",
}

# ── RPG / game terms ────────────────────────────────────────────
RPG = {
    # Roles & archetypes
    "勇者": "Hero",
    "魔王": "Demon Lord",
    "魔物": "Monster",
    "冒険者": "Adventurer",
    "村人": "Villager",
    "町人": "Townsperson",
    "商人": "Merchant",
    "王": "King",
    "王女": "Princess",
    "王子": "Prince",
    "女王": "Queen",
    "領主": "Lord",
    "長老": "Elder",
    "村長": "Village Chief",
    # Locations
    "ギルド": "Guild",
    "ダンジョン": "Dungeon",
    "宿屋": "Inn",
    "酒場": "Tavern",
    "武器屋": "Weapon Shop",
    "道具屋": "Item Shop",
    "防具屋": "Armor Shop",
    "教会": "Church",
    "城": "Castle",
    "王国": "Kingdom",
    "帝国": "Empire",
    "村": "Village",
    "町": "Town",
    "迷宮": "Labyrinth",
    "塔": "Tower",
    "洞窟": "Cave",
    "森": "Forest",
    "砂漠": "Desert",
    "火山": "Volcano",
    "遺跡": "Ruins",
    "神殿": "Temple",
    "墓地": "Graveyard",
    "闘技場": "Arena",
    # Core systems
    "魔法": "Magic",
    "スキル": "Skill",
    "経験値": "EXP",
    "レベルアップ": "Level Up",
    "ゴールド": "Gold",
    "ポーション": "Potion",
    "エリクサー": "Elixir",
    "仲間": "Companion",
    "装備": "Equipment",
    "クエスト": "Quest",
    "依頼": "Request",
    "報酬": "Reward",
    "宝箱": "Treasure Chest",
    "セーブ": "Save",
    "ロード": "Load",
    "ゲームオーバー": "Game Over",
    "全滅": "Annihilation",
    # Menu / UI
    "並び替え": "Sort",
    "最強装備": "Optimal Equipment",
    "大事なもの": "Key Items",
    "ゲーム終了": "Quit Game",
    "コンティニュー": "Continue",
    "ニューゲーム": "New Game",
    "購入する": "Buy",
    "売却する": "Sell",
    "全て外す": "Unequip All",
    "キャンセル": "Cancel",
    "オプション": "Options",
    "タイトルへ": "To Title",
    "ステータス": "Status",
    "やっぱりやめる": "Never Mind",
    "初めから": "Start",
    "回想する": "Recollection",
    "討伐": "Extermination",
    "邪気": "Miasma",
    "所持金": "Money",
    "持ち物": "Inventory",
    "道具": "Items",
    "使う": "Use",
    "捨てる": "Discard",
    "確認": "Confirm",
    "戻る": "Back",
    "決定": "OK",
    "次へ": "Next",
    "閉じる": "Close",
    # Locations
    "避暑地": "Summer Resort",
    "別荘": "Villa",
    "雑木林": "Thicket",
    "川辺": "Riverbank",
}

# ── Combat / battle ──────────────────────────────────────────────
COMBAT = {
    # Targeting
    "敵単体": "Single Enemy",
    "敵全体": "All Enemies",
    "敵１体": "One Enemy",
    "敵２体": "Two Enemies",
    "味方単体": "Single Ally",
    "味方全体": "All Allies",
    "味方一人": "One Ally",
    "使用者": "User",
    "自分": "Self",
    "ランダム": "Random",
    # Actions
    "攻撃": "Attack",
    "防御": "Defend",
    "逃げる": "Escape",
    "逃走": "Escape",
    "戦う": "Fight",
    "アイテム": "Item",
    "必殺技": "Special Move",
    "奥義": "Secret Art",
    "詠唱": "Chanting",
    "召喚": "Summon",
    "回復": "Recovery",
    "治療": "Heal",
    "蘇生": "Revive",
    "復活": "Revival",
    "反撃": "Counter",
    "連続攻撃": "Combo Attack",
    "全体攻撃": "Area Attack",
    "先制攻撃": "Preemptive Strike",
    "不意打ち": "Ambush",
    "会心の一撃": "Critical Hit",
    "会心": "Critical",
    "命中": "Hit",
    "回避": "Evasion",
    "ミス": "Miss",
    # Status effects
    "毒": "Poison",
    "麻痺": "Paralysis",
    "睡眠": "Sleep",
    "暗闇": "Blindness",
    "沈黙": "Silence",
    "混乱": "Confusion",
    "石化": "Petrification",
    "即死": "Instant Death",
    "戦闘不能": "Knocked Out",
    "気絶": "Stunned",
    "出血": "Bleeding",
    "呪い": "Curse",
    "狂戦士": "Berserk",
    "魔法反射": "Magic Reflection",
    "無敵": "Invincible",
    "透明": "Invisible",
    "再生": "Regeneration",
    "弱点": "Weakness",
    "耐性": "Resistance",
    "吸収": "Absorb",
    "バフ": "Buff",
    "デバフ": "Debuff",
    # Elements
    "火": "Fire",
    "氷": "Ice",
    "雷": "Thunder",
    "水": "Water",
    "風": "Wind",
    "土": "Earth",
    "光": "Light",
    "闇": "Darkness",
    "聖": "Holy",
    "無": "None",
    "物理": "Physical",
    "神聖": "Holy",
    "暗黒": "Dark",
    "木": "Wood",
    "地": "Earth",
    "凍結": "Frozen",
    "炎": "Flame",
    "大地": "Earth",
    "ダメージ": "Damage",
    "黒魔法": "Black Magic",
    "白魔法": "White Magic",
    "全体": "All",
    "敵": "Enemy",
    "味方": "Ally",
    "属性": "Attribute",
    # Additional
    "状態異常": "Status Ailment",
    "ターン終了": "End Turn",
    "不死身": "Immortal",
    "激昂": "Enraged",
    "封印": "Seal",
    "祝福": "Blessing",
    "威嚇": "Intimidate",
    "体当たり": "Body Slam",
    "斬撃": "Slash",
    "薙ぎ払い": "Sweeping Slash",
    "突貫": "Rush",
    "隠密": "Stealth",
    "飛行": "Flight",
    "怒り": "Rage",
    "めまい": "Dizziness",
    "硬化": "Hardening",
    "高揚": "Elation",
    "力ため": "Power Charge",
    "自動戦闘": "Auto-Battle",
    "遠距離攻撃": "Ranged Attack",
    "武器破壊": "Weapon Break",
    "見切り": "Parry",
    "吸魂": "Soul Drain",
    "吸血": "Blood Drain",
    "突進": "Charge",
    "瞑想": "Meditation",
    "居合切り": "Iai Slash",
    "盾殴り": "Shield Bash",
    "やけど": "Burn",
    "昏睡": "Coma",
    "深呼吸": "Deep Breath",
}

# ── Stats / parameters ───────────────────────────────────────────
STATS = {
    "最大ＨＰ": "Max HP",
    "最大ＭＰ": "Max MP",
    "ＨＰ": "HP",
    "ＭＰ": "MP",
    "ＴＰ": "TP",
    "攻撃力": "Attack",
    "防御力": "Defense",
    "魔力": "Magic Power",
    "魔法攻撃": "Magic Attack",
    "魔法防御": "Magic Defense",
    "魔防": "Magic Defense",
    "敏捷性": "Agility",
    "敏捷": "Agility",
    "素早さ": "Speed",
    "運": "Luck",
    "命中率": "Hit Rate",
    "回避率": "Evasion Rate",
    "会心率": "Critical Rate",
    "体力": "Stamina",
    "知力": "Intelligence",
    "精神": "Spirit",
    "魅力": "Charisma",
    "力": "Strength",
    "知性": "Intelligence",
    "器用": "Dexterity",
    "職業": "Job",
    "特技": "Special Skill",
    "技": "Technique",
}

# ── Equipment / items ────────────────────────────────────────────
EQUIPMENT = {
    # Slots
    "武器": "Weapon",
    "盾": "Shield",
    "頭防具": "Headgear",
    "身体防具": "Body Armor",
    "腕防具": "Arm Guard",
    "装飾品": "Accessory",
    # Weapon types
    "剣": "Sword",
    "大剣": "Greatsword",
    "短剣": "Dagger",
    "槍": "Spear",
    "斧": "Axe",
    "弓": "Bow",
    "杖": "Staff",
    "本": "Book",
    "鞭": "Whip",
    "爪": "Claws",
    "拳": "Fist",
    "銃": "Gun",
    "刀": "Katana",
    # Items
    "薬草": "Herb",
    "毒消し": "Antidote",
    "万能薬": "Panacea",
    "魔法の鍵": "Magic Key",
    "テント": "Tent",
    "聖水": "Holy Water",
    "煙玉": "Smoke Bomb",
    "鉱石": "Ore",
    "素材": "Material",
    "レシピ": "Recipe",
    "防具": "Armor",
    "帽子": "Hat",
    "服": "Clothes",
    "指輪": "Ring",
}

# ── Eroge status / corruption ──────────────────────────────────
STATUS = {
    "好感度": "Affection",
    "淫乱度": "Lewdness",
    "堕落": "Corruption",
    "純潔": "Purity",
    "貞操": "Chastity",
    "快楽": "Pleasure",
    "感度": "Sensitivity",
    "恥辱": "Shame",
    "屈辱": "Humiliation",
    "服従": "Submission",
    "支配": "Domination",
    "魅了": "Charm",
    "誘惑": "Seduction",
    "欲情": "Lust",
    "発情": "In Heat",
    "興奮": "Arousal",
    "売春": "Prostitution",
    "娼婦": "Prostitute",
    "遊郭": "Brothel",
    "ハーレム": "Harem",
    "逆ハーレム": "Reverse Harem",
    "愛人": "Lover",
    "恋人": "Lover",
    "許嫁": "Fiance",
    "婚約者": "Fiance",
    "理性": "Sanity",
    "性欲": "Libido",
    "絶頂回数": "Orgasms",
    "経験人数": "Partners",
    "射精量": "Cum Amount",
    "恐怖": "Fear",
    "洗脳": "Brainwashing",
    "信頼度": "Trust",
    "妊娠回数": "Pregnancies",
    "告白": "Confession",
    "甘える": "Act Spoiled",
    "おねだり": "Begging",
}

# ── Fantasy races / classes ────────────────────────────────────
RACES = {
    "エルフ": "Elf",
    "ダークエルフ": "Dark Elf",
    "ドワーフ": "Dwarf",
    "獣人": "Beastkin",
    "竜人": "Dragonkin",
    "吸血鬼": "Vampire",
    "サキュバス": "Succubus",
    "インキュバス": "Incubus",
    "ゴブリン": "Goblin",
    "オーク": "Orc",
    "スライム": "Slime",
    "オーガ": "Ogre",
    "リッチ": "Lich",
    "ゾンビ": "Zombie",
    "ケルベロス": "Cerberus",
    "ミノタウロス": "Minotaur",
    "ラミア": "Lamia",
    "ハーピー": "Harpy",
    "アラクネ": "Arachne",
    "ケンタウロス": "Centaur",
    "マーメイド": "Mermaid",
    "妖精": "Fairy",
    "天使": "Angel",
    "悪魔": "Demon",
    "魔族": "Demon Race",
    "人間": "Human",
    "戦士": "Warrior",
    "魔法使い": "Mage",
    "僧侶": "Priest",
    "盗賊": "Thief",
    "騎士": "Knight",
    "聖騎士": "Paladin",
    "暗黒騎士": "Dark Knight",
    "忍者": "Ninja",
    "侍": "Samurai",
    "召喚士": "Summoner",
    "錬金術師": "Alchemist",
    "踊り子": "Dancer",
    "姫騎士": "Princess Knight",
    "女騎士": "Female Knight",
    "女戦士": "Female Warrior",
    "魔女": "Witch",
    "巫女": "Shrine Maiden",
    "シスター": "Sister",
    "メイド": "Maid",
    "くノ一": "Kunoichi",
    "魔術師": "Sorcerer",
    "大魔導士": "Archmage",
    "忍び": "Shinobi",
    # Demons / angels / monsters
    "聖女": "Saintess",
    "上級悪魔": "Arch Demon",
    "魔神": "Devil",
    "魔人": "Demon",
    "睡魔": "Mare",
    "淫魔": "Succubus",
    "夢魔": "Succubus",
    "大天使": "Archangel",
    "権天使": "Principality",
    "能天使": "Power",
    "力天使": "Virtue",
    "主天使": "Dominion",
    "智天使": "Cherub",
    "飛天魔": "Nephilim",
    "堕天使": "Fallen Angel",
    "鬼": "Oni",
    "妖怪": "Yokai",
    "式神": "Shikigami",
    "幽霊": "Ghost",
    "幽鬼": "Revenant",
    "デーモン": "Daemon",
    "ローパー": "Roper",
    "人型": "Humanoid",
    "獣型": "Beast",
    "触手型": "Tentacle Type",
    "軟体型": "Slime Type",
    "虫型": "Insect Type",
    "竜": "Dragon",
    "ドラゴン": "Dragon",
    "ワーウルフ": "Werewolf",
    "グリフォン": "Griffin",
    "ゴーレム": "Golem",
    "トロール": "Troll",
    "キメラ": "Chimera",
    "ワイバーン": "Wyvern",
    "フェニックス": "Phoenix",
    "狼": "Wolf",
    "蜘蛛": "Spider",
    "蝙蝠": "Bat",
    "蛇": "Snake",
}

# ── Clothing / attire ──────────────────────────────────────────
CLOTHING = {
    "鎧": "Armor",
    "ローブ": "Robe",
    "ビキニアーマー": "Bikini Armor",
    "レオタード": "Leotard",
    "制服": "Uniform",
    "水着": "Swimsuit",
    "下着": "Underwear",
    "パンツ": "Panties",
    "ショーツ": "Panties",
    "ブラ": "Bra",
    "ストッキング": "Stockings",
    "ガーターベルト": "Garter Belt",
    "ニーソックス": "Thigh-highs",
    "チャイナドレス": "Cheongsam",
    "バニースーツ": "Bunny Suit",
    "メイド服": "Maid Outfit",
    "巫女服": "Shrine Maiden Outfit",
    "拘束具": "Restraints",
    "首輪": "Collar",
    "手枷": "Handcuffs",
    "目隠し": "Blindfold",
    "猿轡": "Ball Gag",
    "タイツ": "Tights",
    "エプロン": "Apron",
    "スカート": "Skirt",
    "ドレス": "Dress",
    "マント": "Cloak",
    "着物": "Kimono",
    "浴衣": "Yukata",
    "体操服": "Gym Uniform",
    "ブルマ": "Bloomers",
    "スクール水着": "School Swimsuit",
}

# ── Gambling / poker ─────────────────────────────────────────────
GAMBLING = {
    # Card games
    "ポーカー": "Poker",
    "ブラックジャック": "Blackjack",
    "バカラ": "Baccarat",
    "トランプ": "Playing Cards",
    "カード": "Card",
    "手札": "Hand",
    "山札": "Deck",
    "切り札": "Trump Card",
    "ジョーカー": "Joker",
    "ババ抜き": "Old Maid",
    "神経衰弱": "Concentration",
    "大富豪": "President",
    "七並べ": "Sevens",
    # Poker hands
    "ロイヤルストレートフラッシュ": "Royal Flush",
    "ストレートフラッシュ": "Straight Flush",
    "フォーカード": "Four of a Kind",
    "フルハウス": "Full House",
    "フラッシュ": "Flush",
    "ストレート": "Straight",
    "スリーカード": "Three of a Kind",
    "ツーペア": "Two Pair",
    "ワンペア": "One Pair",
    "ブタ": "High Card",
    "役": "Hand",
    # Poker actions
    "レイズ": "Raise",
    "コール": "Call",
    "フォールド": "Fold",
    "チェック": "Check",
    "ベット": "Bet",
    "オールイン": "All-in",
    "ブラフ": "Bluff",
    "ディーラー": "Dealer",
    # Gambling general
    "ギャンブル": "Gambling",
    "賭け": "Bet",
    "賭ける": "To Bet",
    "カジノ": "Casino",
    "スロット": "Slot Machine",
    "ルーレット": "Roulette",
    "サイコロ": "Dice",
    "チップ": "Chips",
    "配当": "Payout",
    "倍率": "Odds",
    "大当たり": "Jackpot",
    "ジャックポット": "Jackpot",
    "一攫千金": "Hitting the Jackpot",
    "勝負": "Match",
    "勝ち": "Win",
    "負け": "Loss",
    "引き分け": "Draw",
    "イカサマ": "Cheating",
    "いかさま": "Cheating",
    # Strip poker / penalty games
    "脱衣ポーカー": "Strip Poker",
    "脱衣麻雀": "Strip Mahjong",
    "脱衣": "Stripping",
    "脱ぐ": "Undress",
    "脱がす": "Strip Someone",
    "脱がされる": "Get Stripped",
    "罰ゲーム": "Penalty Game",
    "罰": "Penalty",
    "一枚脱ぐ": "Take Off One Piece",
    "全裸": "Fully Nude",
    "半裸": "Half-naked",
    "裸": "Naked",
    "恥ずかしい": "Embarrassing",
    "丸見え": "Fully Exposed",
    "見せる": "Show",
    "晒す": "Expose",
    "賭け事": "Gambling",
    "負けたら脱ぐ": "Strip if You Lose",
}

# ── Speaker tags / honorifics ────────────────────────────────────
SPEAKERS = {
    "ご主人様": "Master",
    "マスター": "Master",
    "お嬢様": "Milady",
    "旦那様": "Master",
    "奥様": "Madam",
    "先生": "Teacher",
    "先輩": "Senpai",
    "後輩": "Junior",
    "お兄ちゃん": "Big Brother",
    "お姉ちゃん": "Big Sister",
    "お兄さん": "Mister",
    "お姉さん": "Miss",
    "おじさん": "Old Man",
    "おばさん": "Lady",
    "男": "Man",
    "女": "Woman",
    "少年": "Boy",
    "少女": "Girl",
    "青年": "Young Man",
    "老人": "Old Man",
    "兵士": "Soldier",
    "衛兵": "Guard",
    "店主": "Shopkeeper",
    "受付嬢": "Receptionist",
    "魔法少女": "Magical Girl",
    "ナレーション": "Narration",
    "令嬢": "Young Lady",
    "小悪魔": "Little Devil",
    "付き人": "Attendant",
    "村人たち": "Villagers",
    # School / modern
    "校長": "Principal",
    "職員": "Staff Member",
    "使用人": "Servant",
    "患者": "Patient",
    "大学生": "College Student",
    "高校生": "High School Student",
}

# ── Common expressions ──────────────────────────────────────────
EXPRESSIONS = {
    "くっ": "Kuh...",
    "ふふ": "Fufu",
    "うふふ": "Ufufu",
    "あはは": "Ahaha",
    "えへへ": "Ehehe",
    "くすくす": "Hehe",
    "ぐぬぬ": "Grr...",
    "きゃー": "Kyaa!",
    "やだ": "No Way",
    "ちょっと": "Hey",
    "すごい": "Amazing",
    "やめて": "Stop It",
    "ダメ": "No",
    "だめ": "No",
    "お願い": "Please",
    "ありがとう": "Thank You",
    "ごめんなさい": "I'm Sorry",
    "ごめんね": "Sorry",
    "バカ": "Idiot",
    "馬鹿": "Idiot",
    "うるさい": "Shut Up",
    "助けて": "Help Me",
    "気持ちいい": "It Feels Good",
    "いやらしい": "Naughty",
    "メスガキ": "Bratty Girl",
    "クソガキ": "Brat",
    "ガキ": "Brat",
    "あん": "Ahn~",
    "んっ": "Mmh",
    "痛い": "It Hurts",
    "怖い": "Scary",
    "嬉しい": "Happy",
    "熱い": "Hot",
}

# ── Onomatopoeia / SFX ───────────────────────────────────────────
ONOMATOPOEIA = {
    "ぬるぬる": "Slippery",
    "ぷにぷに": "Soft and Squishy",
    "シコシコ": "Stroking",
    "ビンビン": "Rock Hard",
    "ドピュ": "Spurt",
    "ビクビク": "Twitching",
    "パンパン": "Slapping",
    "ぐちゅぐちゅ": "Squelching",
    "ズボズボ": "Thrusting",
    "つるつる": "Smooth",
    "ドクドク": "Throbbing",
    "ヌルヌル": "Slippery",
    "ピクピク": "Twitching",
    "ズブズブ": "Plunging",
    "ジュボジュボ": "Slurping",
}

# ── All categories with labels ──────────────────────────────────
CATEGORIES = {
    "Body / Anatomy": BODY,
    "Sexual Acts": ACTS,
    "Status / Corruption": STATUS,
    "Fantasy Races / Classes": RACES,
    "Clothing / Attire": CLOTHING,
    "Gambling / Poker": GAMBLING,
    "RPG Terms": RPG,
    "Combat / Battle": COMBAT,
    "Stats / Parameters": STATS,
    "Equipment / Items": EQUIPMENT,
    "Speaker Tags": SPEAKERS,
    "Common Expressions": EXPRESSIONS,
    "Onomatopoeia / SFX": ONOMATOPOEIA,
}


def get_all_defaults() -> dict:
    """Return all default glossary entries merged into one dict."""
    merged = {}
    for cat_entries in CATEGORIES.values():
        merged.update(cat_entries)
    return merged
